var zanzar = {
  paginas: [
    // Tecnologia e desenvolvimento
    'https://manualdousuario.net/',
    'https://manualdousuario.net/orbita',
    'https://tableless.com.br/',
    'https://braziljs.org/',
    'https://www.akitaonrails.com/',
    'https://desenvolvimentoparaweb.com/',
    'https://www.maujor.com/',
    'https://loopinfinito.com.br/',
    'https://blog.caelum.com.br/',
    'https://www.henriquebastos.net/',
    'https://pythonclub.com.br/',
    'https://www.felipefialho.com/',
    'https://vidadesilicio.com.br/',
    'https://canaltech.com.br/',
    'https://olhardigital.com.br/',
    'https://tecnoblog.net/',
    'https://www.tecmundo.com.br/',
    'https://www.hardware.com.br/',
    'https://gizmodo.uol.com.br/',
    // Jornalismo e política
    'https://www.nexojornal.com.br/',
    'https://theintercept.com/brasil/',
    'https://www.agenciapublica.org.br/',
    'https://outraspalavras.net/',
    'https://jacobin.com.br/',
    'https://diplomatique.org.br/',
    'https://www.observatoriodaimprensa.com.br/',
    'https://www.cartacapital.com.br/',
    'https://www.brasildefato.com.br/',
    'https://piaui.folha.uol.com.br/',
    'https://www.poder360.com.br/',
    'https://apublica.org/',
    'https://www.agenciasertao.net/',
    // Cultura e artes
    'https://museudoamanha.org.br/',
    'https://www.itaucultural.org.br/',
    'https://www.sescsp.org.br/',
    'https://www.funarte.gov.br/',
    'https://www.b9.com.br/',
    'https://www.overmundo.com.br/',
    'https://www.culturagenial.com/',
    'https://www.hypeness.com.br/',
    'https://www.vice.com/pt/',
    // Cinema e séries
    'https://www.omelete.com.br/',
    'https://www.papodecinema.com.br/',
    'https://cineplayers.com/',
    'https://www.cinema10.com.br/',
    'https://www.adorocinema.com/',
    'https://www.cinemaemcena.com.br/',
    // Literatura e ideias
    'https://literatortura.com/',
    'https://literaruga.com.br/',
    'https://www.publishnews.com.br/',
    'https://www.filosofia.com.br/',
    'https://universoracionalista.org/',
    'https://www.ceticismo.net/',
    'https://revistacult.uol.com.br/',
    'https://www.ihu.unisinos.br/',
    'https://www.fronteiras.com/',
    // Podcasts e mídia independente
    'https://www.b9.com.br/shows/nerdcast/',
    'https://www.rádio.uol.com.br/',
    'https://radiofobia.com.br/',
    'https://spotniks.com/',
    // Ciência e educação
    'https://www.cienciahoje.com.br/',
    'https://www.superinteressante.com.br/',
    'https://hypescience.com/',
    'https://www.bbc.com/portuguese',
    'https://www.nationalgeographicbrasil.com/',
  ],
  ignorar: []
}
